export const baseUrl = "http://10.39.1.135/multiflags-hrm/public/api/"
export const baseUrlImage = "http://10.39.1.135/multiflags-hrm/public/"
export const baseUrlImage2 = "http://10.39.1.135/multiflags-hrm/"
// export const baseUrl = "https://hrmservices.multiflags.com/api/"
// export const baseUrlImage= "https://hrmservices.multiflags.com/public/"
